import os
import json
import google.generativeai as genai
from src.email_sender import send_email

# ── Configuration ──────────────────────────────────────────────
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "<your-gemini-api-key>")
SENDER_EMAIL    = os.getenv("SENDER_EMAIL",   "<your-gmail@gmail.com>")
SENDER_PASSWORD = os.getenv("SENDER_PASSWORD", "<your-gmail-app-password>")
RECIPIENT_EMAIL = os.getenv("RECIPIENT_EMAIL", "<recipient@gmail.com>")

genai.configure(api_key=GEMINI_API_KEY)
model = genai.GenerativeModel("gemini-2.5-flash-lite")

# ── Step 1: Load Transcript ─────────────────────────────────────
def load_transcript(path: str) -> str:
    with open(path, "r") as f:
        return f.read()

# ── Step 2: Extract Structured Data via Gemini ─────────────────
def analyze_transcript(transcript: str) -> dict:
    prompt = f"""
You are an expert meeting analyst. Analyze the following meeting transcript and return a JSON object with exactly these keys:

{{
  "meeting_title": "string",
  "date": "string",
  "attendees": ["list of names"],
  "key_decisions": ["list of decisions made"],
  "action_items": [
    {{
      "task": "description of task",
      "owner": "person responsible",
      "deadline": "deadline if mentioned, else 'Not specified'",
      "priority": "High / Medium / Low"
    }}
  ],
  "blockers": ["list of blockers or risks mentioned"],
  "summary": "2-3 sentence overall summary of the meeting"
}}

Transcript:
{transcript}

Return ONLY valid JSON. No markdown, no explanation.
"""
    response = model.generate_content(prompt)
    raw = response.text.strip()

    # Strip markdown code fences if Gemini wraps in ```json
    if raw.startswith("```"):
        raw = raw.split("```")[1]
        if raw.startswith("json"):
            raw = raw[4:]

    return json.loads(raw.strip())

# ── Step 3: Format HTML Email ───────────────────────────────────
def format_email(data: dict) -> tuple[str, str]:
    subject = f"📋 Meeting Summary: {data['meeting_title']} — {data['date']}"

    action_rows = "".join(
        f"""<tr>
              <td style="padding:8px;border:1px solid #ddd">{item['task']}</td>
              <td style="padding:8px;border:1px solid #ddd">{item['owner']}</td>
              <td style="padding:8px;border:1px solid #ddd">{item['deadline']}</td>
              <td style="padding:8px;border:1px solid #ddd;color:{'red' if item['priority']=='High' else 'orange' if item['priority']=='Medium' else 'green'}">{item['priority']}</td>
           </tr>"""
        for item in data["action_items"]
    )

    decisions_html = "".join(f"<li>{d}</li>" for d in data["key_decisions"])
    blockers_html  = "".join(f"<li style='color:red'>{b}</li>" for b in data["blockers"]) or "<li>None</li>"
    attendees_html = ", ".join(data["attendees"])

    body = f"""
    <html><body style="font-family:Arial,sans-serif;max-width:700px;margin:auto;color:#333">
      <h2 style="color:#2c3e50">📋 Meeting Summary</h2>
      <p><strong>Meeting:</strong> {data['meeting_title']}</p>
      <p><strong>Date:</strong> {data['date']}</p>
      <p><strong>Attendees:</strong> {attendees_html}</p>

      <h3 style="color:#2980b9">📝 Summary</h3>
      <p>{data['summary']}</p>

      <h3 style="color:#2980b9">✅ Key Decisions</h3>
      <ul>{decisions_html}</ul>

      <h3 style="color:#2980b9">📌 Action Items</h3>
      <table style="border-collapse:collapse;width:100%">
        <tr style="background:#2980b9;color:white">
          <th style="padding:8px;text-align:left">Task</th>
          <th style="padding:8px;text-align:left">Owner</th>
          <th style="padding:8px;text-align:left">Deadline</th>
          <th style="padding:8px;text-align:left">Priority</th>
        </tr>
        {action_rows}
      </table>

      <h3 style="color:#e74c3c">🚧 Blockers / Risks</h3>
      <ul>{blockers_html}</ul>

      <hr style="margin-top:30px"/>
      <p style="font-size:12px;color:#999">This summary was automatically generated by the AI Meeting Summarizer Agent.</p>
    </body></html>
    """
    return subject, body

# ── Step 4: Run the Full Agent Pipeline ────────────────────────
def run_agent(transcript_path: str = "transcript.txt"):
    print("🤖 Agent started...\n")

    print("📄 Step 1: Loading transcript...")
    transcript = load_transcript(transcript_path)

    print("🧠 Step 2: Analyzing transcript with Gemini AI...")
    data = analyze_transcript(transcript)

    print("\n📊 Extracted Data:")
    print(f"  Meeting : {data['meeting_title']}")
    print(f"  Date    : {data['date']}")
    print(f"  Actions : {len(data['action_items'])} action items found")
    print(f"  Blockers: {len(data['blockers'])} blocker(s) found")

    print("\n✉️  Step 3: Formatting email...")
    subject, body = format_email(data)

    print("📤 Step 4: Sending email...")
    send_email(SENDER_EMAIL, SENDER_PASSWORD, RECIPIENT_EMAIL, subject, body)

    print("\n✅ Agent completed successfully!")


if __name__ == "__main__":
    run_agent()
